// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/analytics.proto

package analytics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Analytics service

func NewAnalyticsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Analytics service

type AnalyticsService interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...client.CallOption) (*ProjectResponse, error)
	GetProject(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ProjectResponse, error)
	ListProjects(ctx context.Context, in *Empty, opts ...client.CallOption) (*ListProjectsResponse, error)
	DeleteProject(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...client.CallOption) (*ProjectResponse, error)
	CreateAction(ctx context.Context, in *CreateActionRequest, opts ...client.CallOption) (*ActionResponse, error)
	GetAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ActionResponse, error)
	ListActions(ctx context.Context, in *ListActionsRequest, opts ...client.CallOption) (*ListActionsResponse, error)
	DeleteAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ActionResponse, error)
	TriggerAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*Empty, error)
	ResetAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ActionResponse, error)
	UpdateAction(ctx context.Context, in *UpdateActionRequest, opts ...client.CallOption) (*ActionResponse, error)
}

type analyticsService struct {
	c    client.Client
	name string
}

func NewAnalyticsService(name string, c client.Client) AnalyticsService {
	return &analyticsService{
		c:    c,
		name: name,
	}
}

func (c *analyticsService) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...client.CallOption) (*ProjectResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.CreateProject", in)
	out := new(ProjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) GetProject(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ProjectResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.GetProject", in)
	out := new(ProjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) ListProjects(ctx context.Context, in *Empty, opts ...client.CallOption) (*ListProjectsResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.ListProjects", in)
	out := new(ListProjectsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) DeleteProject(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ProjectResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.DeleteProject", in)
	out := new(ProjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...client.CallOption) (*ProjectResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.UpdateProject", in)
	out := new(ProjectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) CreateAction(ctx context.Context, in *CreateActionRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.CreateAction", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) GetAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.GetAction", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) ListActions(ctx context.Context, in *ListActionsRequest, opts ...client.CallOption) (*ListActionsResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.ListActions", in)
	out := new(ListActionsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) DeleteAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.DeleteAction", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) TriggerAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "Analytics.TriggerAction", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) ResetAction(ctx context.Context, in *RequestById, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.ResetAction", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsService) UpdateAction(ctx context.Context, in *UpdateActionRequest, opts ...client.CallOption) (*ActionResponse, error) {
	req := c.c.NewRequest(c.name, "Analytics.UpdateAction", in)
	out := new(ActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Analytics service

type AnalyticsHandler interface {
	CreateProject(context.Context, *CreateProjectRequest, *ProjectResponse) error
	GetProject(context.Context, *RequestById, *ProjectResponse) error
	ListProjects(context.Context, *Empty, *ListProjectsResponse) error
	DeleteProject(context.Context, *RequestById, *ProjectResponse) error
	UpdateProject(context.Context, *UpdateProjectRequest, *ProjectResponse) error
	CreateAction(context.Context, *CreateActionRequest, *ActionResponse) error
	GetAction(context.Context, *RequestById, *ActionResponse) error
	ListActions(context.Context, *ListActionsRequest, *ListActionsResponse) error
	DeleteAction(context.Context, *RequestById, *ActionResponse) error
	TriggerAction(context.Context, *RequestById, *Empty) error
	ResetAction(context.Context, *RequestById, *ActionResponse) error
	UpdateAction(context.Context, *UpdateActionRequest, *ActionResponse) error
}

func RegisterAnalyticsHandler(s server.Server, hdlr AnalyticsHandler, opts ...server.HandlerOption) error {
	type analytics interface {
		CreateProject(ctx context.Context, in *CreateProjectRequest, out *ProjectResponse) error
		GetProject(ctx context.Context, in *RequestById, out *ProjectResponse) error
		ListProjects(ctx context.Context, in *Empty, out *ListProjectsResponse) error
		DeleteProject(ctx context.Context, in *RequestById, out *ProjectResponse) error
		UpdateProject(ctx context.Context, in *UpdateProjectRequest, out *ProjectResponse) error
		CreateAction(ctx context.Context, in *CreateActionRequest, out *ActionResponse) error
		GetAction(ctx context.Context, in *RequestById, out *ActionResponse) error
		ListActions(ctx context.Context, in *ListActionsRequest, out *ListActionsResponse) error
		DeleteAction(ctx context.Context, in *RequestById, out *ActionResponse) error
		TriggerAction(ctx context.Context, in *RequestById, out *Empty) error
		ResetAction(ctx context.Context, in *RequestById, out *ActionResponse) error
		UpdateAction(ctx context.Context, in *UpdateActionRequest, out *ActionResponse) error
	}
	type Analytics struct {
		analytics
	}
	h := &analyticsHandler{hdlr}
	return s.Handle(s.NewHandler(&Analytics{h}, opts...))
}

type analyticsHandler struct {
	AnalyticsHandler
}

func (h *analyticsHandler) CreateProject(ctx context.Context, in *CreateProjectRequest, out *ProjectResponse) error {
	return h.AnalyticsHandler.CreateProject(ctx, in, out)
}

func (h *analyticsHandler) GetProject(ctx context.Context, in *RequestById, out *ProjectResponse) error {
	return h.AnalyticsHandler.GetProject(ctx, in, out)
}

func (h *analyticsHandler) ListProjects(ctx context.Context, in *Empty, out *ListProjectsResponse) error {
	return h.AnalyticsHandler.ListProjects(ctx, in, out)
}

func (h *analyticsHandler) DeleteProject(ctx context.Context, in *RequestById, out *ProjectResponse) error {
	return h.AnalyticsHandler.DeleteProject(ctx, in, out)
}

func (h *analyticsHandler) UpdateProject(ctx context.Context, in *UpdateProjectRequest, out *ProjectResponse) error {
	return h.AnalyticsHandler.UpdateProject(ctx, in, out)
}

func (h *analyticsHandler) CreateAction(ctx context.Context, in *CreateActionRequest, out *ActionResponse) error {
	return h.AnalyticsHandler.CreateAction(ctx, in, out)
}

func (h *analyticsHandler) GetAction(ctx context.Context, in *RequestById, out *ActionResponse) error {
	return h.AnalyticsHandler.GetAction(ctx, in, out)
}

func (h *analyticsHandler) ListActions(ctx context.Context, in *ListActionsRequest, out *ListActionsResponse) error {
	return h.AnalyticsHandler.ListActions(ctx, in, out)
}

func (h *analyticsHandler) DeleteAction(ctx context.Context, in *RequestById, out *ActionResponse) error {
	return h.AnalyticsHandler.DeleteAction(ctx, in, out)
}

func (h *analyticsHandler) TriggerAction(ctx context.Context, in *RequestById, out *Empty) error {
	return h.AnalyticsHandler.TriggerAction(ctx, in, out)
}

func (h *analyticsHandler) ResetAction(ctx context.Context, in *RequestById, out *ActionResponse) error {
	return h.AnalyticsHandler.ResetAction(ctx, in, out)
}

func (h *analyticsHandler) UpdateAction(ctx context.Context, in *UpdateActionRequest, out *ActionResponse) error {
	return h.AnalyticsHandler.UpdateAction(ctx, in, out)
}
