// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/micro-analytics.proto

package microanalytics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MicroAnalytics service

func NewMicroAnalyticsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MicroAnalytics service

type MicroAnalyticsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MicroAnalytics_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (MicroAnalytics_PingPongService, error)
}

type microAnalyticsService struct {
	c    client.Client
	name string
}

func NewMicroAnalyticsService(name string, c client.Client) MicroAnalyticsService {
	return &microAnalyticsService{
		c:    c,
		name: name,
	}
}

func (c *microAnalyticsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "MicroAnalytics.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microAnalyticsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (MicroAnalytics_StreamService, error) {
	req := c.c.NewRequest(c.name, "MicroAnalytics.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microAnalyticsServiceStream{stream}, nil
}

type MicroAnalytics_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type microAnalyticsServiceStream struct {
	stream client.Stream
}

func (x *microAnalyticsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *microAnalyticsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microAnalyticsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microAnalyticsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microAnalyticsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microAnalyticsService) PingPong(ctx context.Context, opts ...client.CallOption) (MicroAnalytics_PingPongService, error) {
	req := c.c.NewRequest(c.name, "MicroAnalytics.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microAnalyticsServicePingPong{stream}, nil
}

type MicroAnalytics_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type microAnalyticsServicePingPong struct {
	stream client.Stream
}

func (x *microAnalyticsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *microAnalyticsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *microAnalyticsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microAnalyticsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microAnalyticsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *microAnalyticsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MicroAnalytics service

type MicroAnalyticsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, MicroAnalytics_StreamStream) error
	PingPong(context.Context, MicroAnalytics_PingPongStream) error
}

func RegisterMicroAnalyticsHandler(s server.Server, hdlr MicroAnalyticsHandler, opts ...server.HandlerOption) error {
	type microAnalytics interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type MicroAnalytics struct {
		microAnalytics
	}
	h := &microAnalyticsHandler{hdlr}
	return s.Handle(s.NewHandler(&MicroAnalytics{h}, opts...))
}

type microAnalyticsHandler struct {
	MicroAnalyticsHandler
}

func (h *microAnalyticsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicroAnalyticsHandler.Call(ctx, in, out)
}

func (h *microAnalyticsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicroAnalyticsHandler.Stream(ctx, m, &microAnalyticsStreamStream{stream})
}

type MicroAnalytics_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type microAnalyticsStreamStream struct {
	stream server.Stream
}

func (x *microAnalyticsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microAnalyticsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microAnalyticsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microAnalyticsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microAnalyticsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *microAnalyticsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicroAnalyticsHandler.PingPong(ctx, &microAnalyticsPingPongStream{stream})
}

type MicroAnalytics_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type microAnalyticsPingPongStream struct {
	stream server.Stream
}

func (x *microAnalyticsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *microAnalyticsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microAnalyticsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microAnalyticsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microAnalyticsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *microAnalyticsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
